### ISSUE TITLE
User test@gmail.com not found

### ISSUE THREAD

**Issue by suiyan538** [wandb/server#106]
/usr/local/bin/local password test@gmail.com
This problem occurs when adding users manually
User test@gmail.com not found
![image](https://user-images.githubusercontent.com/120363294/211529886-497fd3fa-093c-4d15-9486-259a06f7b704.png)

**Comment by luisbergua** [comment]
Hi @suiyan538, thanks for reporting this! Could you share with me what version of `wandb local` are you using?

**Comment by suiyan538** [comment]
> local

I am using the latest version of wandb-local, and I also found that when I set the project I created to public in wandb-local, others cannot access it.
![image](https://user-images.githubusercontent.com/120363294/211789322-dfc5212a-8d0b-4f9a-9c22-fc2d7ea4778e.png)

**Comment by suiyan538** [comment]
> 
I did this by following the link below
https://github.com/wandb/local/issues/66

**Comment by luisbergua** [comment]
Hi @suiyan538, I'm sorry for the delay here. I'm looking at the issue when adding users manually. You can also add a user from the /admin/users page. Regarding the issue with public rojects, you can give access to everyone to a public project by setting the environment variable `GORILLA_ALLOW_ANONYMOUS_PUBLIC_PROJECTS` to True in your local instance
```
- name: GORILLA_ALLOW_ANONYMOUS_PUBLIC_PROJECTS
  value: "true" 
```

**Comment by suiyan538** [comment]
hi@luisbergua ，I set the environment variable, but others still can't access it.
The following are the environment variables I set. I used two ways to set the environment variables, but it didn't work.
![image](https://user-images.githubusercontent.com/120363294/215252314-494f3c08-87f5-468d-b79b-4c3832ec85dd.png)
![image](https://user-images.githubusercontent.com/120363294/215252484-449acda4-9032-48b9-a95a-fe6b2d33e2e9.png)

The following is the problem when accessing
![image](https://user-images.githubusercontent.com/120363294/215252340-9ccaee94-0ae7-4754-9f9e-45722d5d4d3f.png)

**Comment by suiyan538** [comment]
> Hi @suiyan538, I'm sorry for the delay here. I'm looking at the issue when adding users manually. You can also add a user from the /admin/users page. Regarding the issue with public rojects, you can give access to everyone to a public project by setting the environment variable `GORILLA_ALLOW_ANONYMOUS_PUBLIC_PROJECTS` to True in your local instance
> 
> ```
> - name: GORILLA_ALLOW_ANONYMOUS_PUBLIC_PROJECTS
>   value: "true" 
> ```

hi@luisbergua ，I set the environment variable, but others still can't access it.
The following are the environment variables I set. I used two ways to set the environment variables, but it didn't work.
image
image

The following is the problem when accessing
image

**Comment by luisbergua** [comment]
Hi @suiyan538, thanks for your answer! Could you please try setting this variable when running the docker container like showed [here](https://docs.wandb.ai/guides/self-hosted/setup/on-premise-baremetal#docker) and see if it works? This should set this variable for the hole instance.

**Comment by suiyan538** [comment]
> Hi @suiyan538, thanks for your answer! Could you please try setting this variable when running the docker container like showed [here](https://docs.wandb.ai/guides/self-hosted/setup/on-premise-baremetal#docker) and see if it works? This should set this variable for the hole instance.

I didn't understand this command very much, so I thought, what needs to be done so that unregistered users can also access public projects running on my locally deployed wandb.

**Comment by luisbergua** [comment]
Hi @suiyan538, sorry for not explaining this properly. You can set it running a command like:
```
docker run --rm -d \
   -e GORILLA_ALLOW_ANONYMOUS_PUBLIC_PROJECTS=true \
   -e HOST=https://your_dns_name/ \
   -e LICENSE=XXXXX \
   -p 8080:8080 --name wandb-local wandb/local 
```
as the -e tag is for env varibles. Your container would also need access to the public internet to share reports like this. Could you please run your local instance like this and see if it works?

**Comment by suiyan538** [comment]
> 

Thank you very much for your reply, now the problem is solved.

**Comment by suiyan538** [comment]
> Hi @suiyan538, sorry for not explaining this properly. You can set it running a command like:
> 
> ```
> docker run --rm -d \
>    -e GORILLA_ALLOW_ANONYMOUS_PUBLIC_PROJECTS=true \
>    -e HOST=https://your_dns_name/ \
>    -e LICENSE=XXXXX \
>    -p 8080:8080 --name wandb-local wandb/local 
> ```
> 
> as the -e tag is for env varibles. Your container would also need access to the public internet to share reports like this. Could you please run your local instance like this and see if it works?

Thank you very much for your reply, now the problem is solved.

**Comment by luisbergua** [comment]
Thanks for confirming this @suiyan538! I'll then close the ticket, thanks for your patience!
