### ISSUE TITLE
Private deployment require login without signup

### ISSUE THREAD

**Issue by fecet** [wandb/server#109]
I'm trying to start a local wandb server, but have some trouble.  
Goint to "localhost:8080" after start
```
wandb server start
```
take me to a login page
![image](https://user-images.githubusercontent.com/41792945/219338342-aa2b17ea-809c-42d0-aa66-9c11cda1e9e1.png)

But I haven't signup any account yet, and I don't find any relevant document about it, which seems crucial.

Relevant issue including #64 #91, but solution mentioned not work for me. Trying to add a new account
```
/usr/local/bin/local password test@gmail.com
```
give me
```
User test@gmail.com not found
```

**Comment by nate-wandb** [comment]
Hi @fecet, I'm not entirely sure what may have caused this but if you don't have any data logged to the server yet, I would delete the Docker volume and then restart the server. This should give you an option to sign up when you start the server. 

If that doesn't work could you let me know what version of `wandb server` you are trying to start? This should be listed in the tags of the image. 

Thank you,
Nate

**Comment by nate-wandb** [comment]
Hi @fecet, were you able to get this resolved by deleting the volume or is this still an issue?

Thank you,
Nate

**Comment by fecet** [comment]
Complete delete docker images and restart works.
