### ISSUE TITLE
Wandb server : User setting error - Application Error Unable to reach the backend api. If this perists, check the system logs.

### ISSUE THREAD

**Issue by AJ-ajay-AY** [wandb/server#117]
Hi Team,

I am facing an issue while setting up Wandb server on a AWS EC2 machine for a team trial .

**Installation and server start:**
command : pip install wandb 
version : version 0.15.3
start command: wandb server start
using on default port

**System details**
server and os : AWS Ec2 , os Amazon linux 2
network: private vpc

I opened up localhost:8080 , created a user and went over to System Settings to set up license keys, S3 storage and MysqlDb . I tried all possible options for _frontend host_ : http://10.5.240.147:8080 and http://127.0.0.1:8080 . I always keep getting this error 

Application Error
Unable to reach the backend api. If this perists, check the system logs

<img width="1317" alt="Screenshot 2023-05-31 at 4 33 56 PM" src="https://github.com/wandb/server/assets/30647144/2e25d6f7-4ed7-4a8d-853f-6c11eab934ba">

I tried resolving by looking at resolved GitHub issues - No luck

**Comment by luisbergua** [comment]
Hi @AJ-ajay-AY, thanks for reporting this! Would it be possible to share the Debug Bundle of your instance so I can have a look at it and see why this error is raising? An admin of the instance can get it from the `/system-admin` page -> top right corner W&B icon -> Debug Bundle. Feel free to send it to my email luis.bergua@wandb.com

**Comment by AJ-ajay-AY** [comment]
> 

Sent on your mail id .

**Comment by AJ-ajay-AY** [comment]
> Hi @AJ-ajay-AY, thanks for reporting this! Would it be possible to share the Debug Bundle of your instance so I can have a look at it and see why this error is raising? An admin of the instance can get it from the `/system-admin` page -> top right corner W&B icon -> Debug Bundle. Feel free to send it to my email [luis.bergua@wandb.com](mailto:luis.bergua@wandb.com)

Hope you got the email .

**Comment by twmht** [comment]
I got the same errors, where can i check the system log?

**Comment by twmht** [comment]
from docker logs

```
mc: <ERROR> Unable to set 'notify_redis address=127.0.0.1:6379 format=access queue_limit=10000 queue_dir=/etc/minio/events key=filemetadata' to server. Access Denied. (Prefix access is denied: .minio.sys/config/config.json).
```

**Comment by AJ-ajay-AY** [comment]
Any progress or movement on this @luisbergua  ?

**Comment by luisbergua** [comment]
Hi @AJ-ajay-AY, apologies for the delay on this! Would you mind sending the bundle again? It seems to be an invalid zip file and I'm unable to expand it so cannot check the logs. @twmht you can get the Debug Bundle from the `/system-admin` page -> top right corner W&B icon -> Debug Bundle. Would you mind sending it to luis.bergua@wandb.com?

**Comment by sydholl** [comment]
WandB Internal User commented: 
AJ-ajay-AY commented: 
> 

Sent on your mail id .

**Comment by sydholl** [comment]
WandB Internal User commented: 
AJ-ajay-AY commented: 
> Hi @AJ-ajay-AY, thanks for reporting this! Would it be possible to share the Debug Bundle of your instance so I can have a look at it and see why this error is raising? An admin of the instance can get it from the `/system-admin` page -> top right corner W&B icon -> Debug Bundle. Feel free to send it to my email [luis.bergua@wandb.com](mailto:luis.bergua@wandb.com)

Hope you got the email .

**Comment by sydholl** [comment]
WandB Internal User commented: 
twmht commented: 
I got the same errors, where can i check the system log?

**Comment by luisbergua** [comment]
Hi @AJ-ajay-AY! Could you please share the Bundle again? I wasn't able to open the one that I received as the zip file was corrupted

**Comment by sydholl** [comment]
WandB Internal User commented: 
sydholl commented: 
WandB Internal User commented: 
AJ-ajay-AY commented: 
> Hi @AJ-ajay-AY, thanks for reporting this! Would it be possible to share the Debug Bundle of your instance so I can have a look at it and see why this error is raising? An admin of the instance can get it from the `/system-admin` page -> top right corner W&B icon -> Debug Bundle. Feel free to send it to my email [luis.bergua@wandb.com](mailto:luis.bergua@wandb.com)

Hope you got the email .
