### ISSUE TITLE
RunsStateDeltaQuery responded 504 gateway time out

### ISSUE THREAD

**Issue by yh-xu** [wandb/server#122]
I delolyed wandb server on local host. It took more than 1 min to render page of runs and chart.  It seems request of RunsStateDeltaQuery got 504 gateway timeout and thus stuck the following queries.  What shall I do to get rid of this problem?

**Comment by yh-xu** [comment]
![C2}MTS@HZ`1Y K%PM6B5K{R](https://github.com/wandb/server/assets/59196087/7a00e15b-f2be-4a36-863b-be2a699bd384)

**Comment by sydholl** [comment]
WandB Internal User commented: 
yh-xu commented: 
![C2}MTS@HZ`1Y K%PM6B5K{R](https://github.com/wandb/server/assets/59196087/7a00e15b-f2be-4a36-863b-be2a699bd384)

**Comment by yh-xu** [comment]
Any ideas?

**Comment by sydholl** [comment]
WandB Internal User commented: 
yh-xu commented: 
Any ideas?

**Comment by yh-xu** [comment]
> WandB Internal User commented: yh-xu commented: Any ideas?

Are you posting some link or image? Somehow your reply is not visible.

**Comment by sydholl** [comment]
WandB Internal User commented: 
yh-xu commented: 
> WandB Internal User commented: yh-xu commented: Any ideas?

Are you posting some link or image? Somehow your reply is not visible.

**Comment by yh-xu** [comment]
request RunsStateDeltaQuery sometimes got 500 response with error message "context deadline exceeded"

**Comment by thanos-wandb** [comment]
Hi @yh-xu thank you for reporting this issue. We will need more information in order to troubleshoot any issues you're experiencing. Is the issue about slow performance of the App, or it won't load? Could you please provide some more information:
- how you deployed wandb server, did you use Docker?
- what's your current W&B Local/Server version?
- have you connected to any external bucket or MySQL database?
- about how many projects/runs/data points you've logged?
- what's the allocated resources, RAM, CPU?
- could you please send a screenshot from the `<host-url>/system-admin` page? (without showing any information such as key)
- from the same page, accessed also from System Settings option, could you please click again on top right and download the `Debug Bundle` and attach here?

**Comment by yh-xu** [comment]
It's aboaut slow performance. The whole page was loaded for more than 1 min.

- I use docker image to deploy local wandb server, version 0.36.0
- It's using MySQL locally in image, with host local path mounted.
- Currently I've got 3 projects / 3k+ runs logged.
- 256 cpu and 500G+ RAM allocated

![A084WL2(7UDAUD7$UM}2 XH](https://github.com/wandb/server/assets/59196087/7375b71f-1d7f-4af5-a4d8-d4fdae3b1f0d)

**Comment by yh-xu** [comment]
[debug0706.zip](https://github.com/wandb/server/files/11963074/debug0706.zip)

**Comment by yh-xu** [comment]
Have you got any ideas of slow performance in graphql request ?

**Comment by yh-xu** [comment]
I turned to an external-mysql service and synced 200+ runs to the new deployment. Normally a run logs 1k~5k data points. I'm still seeing slow performance of page rendering and RunsStateDeltaQuery error in graphql request.

**Comment by thanos-wandb** [comment]
Hi @yh-xu thanks a lot for detailed information, the zipped debug bundle doesn't seem to be downloadable. I have reached out to you by email, could you please send it there so that we can investigate further? thank you!

**Comment by thanos-wandb** [comment]
Hi @yh-xu thanks for sending through the debug bundle by email. There are some errors in the logs where the connection to license server would timeout. This might have to do with your instance configurations as it's trying to contact `https://http:%2F%2Flocalhost:8081`. Have you configured a host where you're deploying the App, what's the docker command you're using?

**Comment by thanos-wandb** [comment]
Hi @yh-xu we have released a new W&B Server/Local `v0.37.0`. Could you please try to pull the latest image and upgrade, and see if that now works for you?

**Comment by yh-xu** [comment]
The containe is deployed in k8s cluster with containerd as runtime. Host is configured by exporting environment variable.
I will try new W&B server/local v0.37.0 today. One things is my trial license will be expired in no more than 2 days. Would you extend my license ?
________________________________
发件人: thanos-wandb ***@***.***>
发送时间: 2023年7月12日 21:22
收件人: wandb/server ***@***.***>
抄送: yh-xu ***@***.***>; Mention ***@***.***>
主题: Re: [wandb/server] RunsStateDeltaQuery responded 504 gateway time out (Issue #122)


Hi @yh-xu<https://github.com/yh-xu> we have released a new W&B Server/Local v0.37.0. Could you please try to pull the latest image and upgrade, and see if that now works for you?

―

**Comment by yh-xu** [comment]
My server is deployed on port 8080.
You mentioned " it's trying to contact https://http:%2F%2Flocalhost:8081. " Does that mean I need configure host on port 8081, or it's another server address need be deployed?
________________________________
发件人: Xu Yanhong ***@***.***>
发送时间: 2023年7月12日 23:01
收件人: wandb/server ***@***.***>; wandb/server ***@***.***>
抄送: Mention ***@***.***>
主题: 回复: [wandb/server] RunsStateDeltaQuery responded 504 gateway time out (Issue #122)

The containe is deployed in k8s cluster with containerd as runtime. Host is configured by exporting environment variable.
I will try new W&B server/local v0.37.0 today. One things is my trial license will be expired in no more than 2 days. Would you extend my license ?
________________________________
发件人: thanos-wandb ***@***.***>
发送时间: 2023年7月12日 21:22
收件人: wandb/server ***@***.***>
抄送: yh-xu ***@***.***>; Mention ***@***.***>
主题: Re: [wandb/server] RunsStateDeltaQuery responded 504 gateway time out (Issue #122)


Hi @yh-xu<https://github.com/yh-xu> we have released a new W&B Server/Local v0.37.0. Could you please try to pull the latest image and upgrade, and see if that now works for you?

―

**Comment by thanos-wandb** [comment]
Hi @yh-xu I have reached out to you by email in order to get information on your license and check this for you. In the meantime, please let us know if you're still running into any issues after upgrading to `v0.37.0`.

**Comment by yh-xu** [comment]
The org of my license is hai-platform.
I'm working on the new version now. Would you suggest what server port should I configure ? You mentioned " it's trying to contact https://http:%2F%2Flocalhost:8081. " Does that mean I need configure host on port 8081, or it's another server address need be deployed?
________________________________
发件人: thanos-wandb ***@***.***>
发送时间: 2023年7月12日 23:42
收件人: wandb/server ***@***.***>
抄送: yh-xu ***@***.***>; Mention ***@***.***>
主题: Re: [wandb/server] RunsStateDeltaQuery responded 504 gateway time out (Issue #122)


Hi @yh-xu<https://github.com/yh-xu> I have reached out to you by email in order to get information on your license and check this for you. In the meantime, please let us know if you're still running into any issues after upgrading to v0.37.0.

―

**Comment by yh-xu** [comment]
I got quite a few errors in v0.37.0
debug bundle attached
[cid:b8b95734-82df-4ce7-8735-357d9d27e092]
________________________________
发件人: Xu Yanhong ***@***.***>
发送时间: 2023年7月13日 9:12
收件人: wandb/server ***@***.***>; wandb/server ***@***.***>
抄送: Mention ***@***.***>
主题: 回复: [wandb/server] RunsStateDeltaQuery responded 504 gateway time out (Issue #122)

The org of my license is hai-platform.
I'm working on the new version now. Would you suggest what server port should I configure ? You mentioned " it's trying to contact https://http:%2F%2Flocalhost:8081. " Does that mean I need configure host on port 8081, or it's another server address need be deployed?
________________________________
发件人: thanos-wandb ***@***.***>
发送时间: 2023年7月12日 23:42
收件人: wandb/server ***@***.***>
抄送: yh-xu ***@***.***>; Mention ***@***.***>
主题: Re: [wandb/server] RunsStateDeltaQuery responded 504 gateway time out (Issue #122)


Hi @yh-xu<https://github.com/yh-xu> I have reached out to you by email in order to get information on your license and check this for you. In the meantime, please let us know if you're still running into any issues after upgrading to v0.37.0.

―

**Comment by wenjun93** [comment]
It seems :8081 is served by `megabinary gorilla` process, see through the gorilla.log, there is timeout processing the request RunsStateDeltaQuery
`
{"level":"INFO","time":"2023-07-13T03:34:39.300607969Z","info":{"program":"gorilla","source":"mnt/ramdisk/core/services/gorilla/api/handler/relay.go:233","pid":1055},"data":{"operationName":"RunsStateDeltaQuery","authUser":"xxx","latencyNs":120807404571,"statusCode":500,"operationName":"RunsStateDeltaQuery","authUser":"xxx","latencyStr":"2m0.807404571s"},"message":"Graphql operation RunsStateDeltaQuery for user wenjun finished in 2m0.807404571s","dd.trace_id":"12545692706916674541"}
`

**Comment by yh-xu** [comment]
Hi all,

v0.37.0 didn't resolve my problem and showed up a few more errors. Would you suggest a proper configuration?
________________________________
发件人: wenjun93 ***@***.***>
发送时间: 2023年7月13日 11:40
收件人: wandb/server ***@***.***>
抄送: yh-xu ***@***.***>; Mention ***@***.***>
主题: Re: [wandb/server] RunsStateDeltaQuery responded 504 gateway time out (Issue #122)


It seems :8081 is served by megabinary gorilla process, see through the gorilla.log, there is timeout processing the request RunsStateDeltaQuery
{"level":"INFO","time":"2023-07-13T03:34:39.300607969Z","info":{"program":"gorilla","source":"mnt/ramdisk/core/services/gorilla/api/handler/relay.go:233","pid":1055},"data":{"operationName":"RunsStateDeltaQuery","authUser":"xxx","latencyNs":120807404571,"statusCode":500,"operationName":"RunsStateDeltaQuery","authUser":"xxx","latencyStr":"2m0.807404571s"},"message":"Graphql operation RunsStateDeltaQuery for user wenjun finished in 2m0.807404571s","dd.trace_id":"12545692706916674541"}

―

**Comment by thanos-wandb** [comment]
Hi @yh-xu thanks for the update, the Debug Bundle isn't attached above, could you please send it to the previous email and I will sync with the Solutions Architect team to review it for any mis-configurations.

**Comment by yh-xu** [comment]
attached
________________________________
发件人: thanos-wandb ***@***.***>
发送时间: 2023年7月14日 17:33
收件人: wandb/server ***@***.***>
抄送: yh-xu ***@***.***>; Mention ***@***.***>
主题: Re: [wandb/server] RunsStateDeltaQuery responded 504 gateway time out (Issue #122)


Hi @yh-xu<https://github.com/yh-xu> thanks for the update, the Debug Bundle isn't attached above, could you please send it to the previous email and I will sync with the Solutions Architect team to review it for any mis-configurations.

―

**Comment by yh-xu** [comment]
Hello,

Have you got debug buncle attached in previous email? Would you suggest what mis-configuration to correct?


________________________________
发件人: Xu Yanhong ***@***.***>
发送时间: 2023年7月15日 11:19
收件人: wandb/server ***@***.***>; wandb/server ***@***.***>
抄送: Mention ***@***.***>
主题: 回复: [wandb/server] RunsStateDeltaQuery responded 504 gateway time out (Issue #122)

 attached
________________________________
发件人: thanos-wandb ***@***.***>
发送时间: 2023年7月14日 17:33
收件人: wandb/server ***@***.***>
抄送: yh-xu ***@***.***>; Mention ***@***.***>
主题: Re: [wandb/server] RunsStateDeltaQuery responded 504 gateway time out (Issue #122)


Hi @yh-xu<https://github.com/yh-xu> thanks for the update, the Debug Bundle isn't attached above, could you please send it to the previous email and I will sync with the Solutions Architect team to review it for any mis-configurations.

―

**Comment by thanos-wandb** [comment]
Hi @yh-xu I have emailed you last week twice with the new extended trial license key, and for requesting the Debug Bundle by email. Could you please email back with the Debug Bundle, as it won't work here in GitHub?

**Comment by yh-xu** [comment]
I already attached debug bundle in email. Can you check email thread?

**Comment by yh-xu** [comment]
Have you got any ideas about slow query problem?

**Comment by thanos-wandb** [comment]
Hi @yh-xu I was wondering if you're in an air-gapped environment? After internal discussion with our SA team, they've suggested to turn off telemetry by setting `DISABLE_TELEMETRY=true` in the container. Could you please try this recommendation, and also check if upgrading to our most recent W&B Server v0.39.0 would help with slow queries?

**Comment by yh-xu** [comment]
Turning off telemetry doesn't help.

**Comment by yh-xu** [comment]
This issue of query timeout prevents me from using wandb properly in a self-managed deployment. We guess some requests may go out for internet access which is not available in our private environment.

**Comment by thanos-wandb** [comment]
Hi @yh-xu sorry to hear turning off telemetry didn't work for you. There might still be some configurations to make it work properly in such environment. Could you please upgrade to 0.39.0 and send us the new debug bundle by email, and I will pass it to our Solutions Architect team to further review.

**Comment by yh-xu** [comment]
Have you got any update?

**Comment by thanos-wandb** [comment]
Hi @yh-xu sorry for late reply here, the team has reviewed the logs and it seems there's an inconsistency in the URL you're trying to use to login and configured in the system settings.

This is how the HOST variable is configured:
`"value": "https://wandb.deepseek.com/"`

and this is the host being requested in the logs:
`"url":"http://10.2.208.15:8080/oidc/login"`

If the HOST differs from the URL, we could expect some weird behavior. In the logs it shows several messages like these that ends up with a status code 400:
`"message":"Request origin not allowed: http://10.2.208.15:8080/"`

Could you please confirm what's the intended HOST, and if you could please change this to match? Would this work for you?

**Comment by yh-xu** [comment]
No luck. I still got slow query.

I confirmed in current deployment:
1. HOST variable is consistent with request url . checking in file  instance-state.json:
![1691668149670](https://github.com/wandb/server/assets/59196087/9caa1ffe-0914-4893-8df7-0c3bf9718887)
and no "request origin not allowed" error logged.

2. telemetry is turned off , as in file local.log
![1691668221435](https://github.com/wandb/server/assets/59196087/aa7eced7-2bc3-4265-a21b-0ae6310817dd)

I still got slow query when loading workspace runs or searching by name in regex. 
Mostly the request of RunsStateDeltaQuery finished in more than 2min and thus slowdown the whole page rendering. 
![1691668527956](https://github.com/wandb/server/assets/59196087/dbf97dd3-20d6-44eb-b693-8443bba6885e)

**Comment by yh-xu** [comment]
Besides, I found error log of  "message":"user is disabled" in gorilla.log
![1691669044536](https://github.com/wandb/server/assets/59196087/77e93a8a-61ff-4405-ac91-975192b6b691)
what does it mean and should it affect any query?

**Comment by yh-xu** [comment]
I just send another email to attach debug bundle and recording of the slow query phenomenon.

**Comment by yh-xu** [comment]
Is there some way to profile sever side performance? Can you provide a version to support pprof and then we can dump cpu profile ?

**Comment by thanos-wandb** [comment]
Thanks so much @yh-xu for providing all these details, and the screen recording is really helpful to understand more the issue you're still experiencing, sorry for any trouble this is causing you. I have updated the team internally and we will reach back to you here once the new information is reviewed.

**Comment by yh-xu** [comment]
Please extend my license for one more month as the problem is not resolved yet.

**Comment by yh-xu** [comment]
Have you got some findings?

**Comment by thanos-wandb** [comment]
Hi @yh-xu apologies for late response here. The license issue should be resolved for you as I updated it. Regarding the slow performance, we have included a profiling option in latest release W&B Server 0.40.0. Sorry to ask you again but could you please upgrade to that version so that you can use this tool?

Could you then try to append PERF_LOGGING as a query param, eg: `https://<host-url>/<entity>/<project>?PERF_LOGGING` to any page of the App that has a degraded performance? 

Getting the console logs would have more debug information that can help us understand which are the slow queries. If you could grab all console logs and share with us would be great. 

For additional information, I was wondering if you could make a project with couple of runs and few panels, does this also load very slow for you?

**Comment by yh-xu** [comment]
[10.2.102.137-1692842611348.log](https://github.com/wandb/server/files/12426173/10.2.102.137-1692842611348.log)
[10.2.102.137-1692858334426.log](https://github.com/wandb/server/files/12426174/10.2.102.137-1692858334426.log)

**Comment by yh-xu** [comment]
I collected some console log with perf_logging on. It indicated some long tasks 
![1692859315187](https://github.com/wandb/server/assets/59196087/00ad32fb-f05c-495b-8fd3-f9577a84bd46)

**Comment by yh-xu** [comment]
> Hi @yh-xu apologies for late response here. The license issue should be resolved for you as I updated it. Regarding the slow performance, we have included a profiling option in latest release W&B Server 0.40.0. Sorry to ask you again but could you please upgrade to that version so that you can use this tool?
> 
> Could you then try to append PERF_LOGGING as a query param, eg: `https://<host-url>/<entity>/<project>?PERF_LOGGING` to any page of the App that has a degraded performance?
> 
> Getting the console logs would have more debug information that can help us understand which are the slow queries. If you could grab all console logs and share with us would be great.
> 
> For additional information, I was wondering if you could make a project with couple of runs and few panels, does this also load very slow for you?

I have another project with 100+ runs and 2 metric charts , and it also reponded slow graphql query.

**Comment by thanos-wandb** [comment]
Hi @yh-xu apologies for late response here. Does this slow performance still occurs for you? I wanted to follow-up on this with instruction how to use `pprof` that you previously requested and get some more debugging information. 

Could you run the attached shell script (please rename from `.txt` to `.sh`) within your wandb local docker container to collect some more information?

It leverages `GORILLA_PPROF_ADDR` environment variable so you would wanna have that enabled.

Here are the steps you would have to follow:
- Run the container with `GORILLA_PPROF_ADDR=8085`
- `docker cp` this shell script into the container
- Check the slow loading workspaces
- run attached shell script from within the container

This script in its default configuration should run for 1 minute, please let it complete its runtime and share the `PPROF.tar.gz` file that it generates. You should be also able to use `htop` to check resources. 

I hope this helps! Please let me know if you had any questions on this.

**Comment by thanos-wandb** [comment]
[generate_profile.txt](https://github.com/wandb/server/files/12622398/generate_profile.txt)

**Comment by thanos-wandb** [comment]
Hi @yh-xu I wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by thanos-wandb** [comment]
Hi @yh-xu  since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
