### ISSUE TITLE
Unable to renew my expired personal license 

### ISSUE THREAD

**Issue by JiarunLiu** [wandb/server#127]
Hi, I'm using wandb server with docker. Recently, I noticed that my license is expired:

<img width="912" alt="image" src="https://github.com/wandb/server/assets/42335666/e27d1210-d341-4b36-8e2e-450089cf360b">

I tried to renew my license at `https://deploy.wandb.ai/deploy`. However, I didn't find the entry to renew my license. How can I renew my license? 

Besides, when I click the `Update settings` button at `/system-admin` page. The following error occurs:

<img width="588" alt="image" src="https://github.com/wandb/server/assets/42335666/7b3c5d4b-f502-4017-8684-bbec477c226e">

**Comment by thanos-wandb** [comment]
Hi @JiarunLiu thank you for contacting us. I have extended your personal license for a further year. Regarding the Application error message, this shows up when you click multiple times in the Update settings button. Can you please copy-paste your license from Deploy manager, and click in the button only once? Would it work for you?

**Comment by JiarunLiu** [comment]
Thank you. But it did not work for me. I paste the new license in `/system-admin` then I click the `Update settings` button only once. The Application error message still shows up. I can't use wandb after updating my license on the web page. It still notices me "License Expired". Is there any possible reason & solution? I'm using `wandb/local:0.42.0` from dockerhub to create my wandb server.

<img width="1083" alt="image" src="https://github.com/wandb/server/assets/42335666/d043cece-ffcf-47db-8032-65cac0c61304">

<img width="921" alt="image" src="https://github.com/wandb/server/assets/42335666/a6977477-e3c2-4a50-aea2-dba24d3de761">

**Comment by thanos-wandb** [comment]
Hi @JiarunLiu I can see in the green box that the license has been applied successfully. What remains to be configured is to set the `Frontend Host`. Can you please click in the `Click here to update` link inside the red box?

**Comment by JiarunLiu** [comment]
Yes, I have tried to update the frontend host, but it didn't work either. The same "Application Error" shows when I click the `Click here to update` link. The correct frontend host can show in the box but it disappears when I refresh the page after `Update settings`. Also, the `/system-admin` comes back to this status when I refresh the web page after settings. So I'm not sure the license was actually applied successfully or if it was caused by some other problems.

<img width="746" alt="image" src="https://github.com/wandb/server/assets/42335666/a70d1c93-ccf1-4718-9501-caea34abaf17">

**Comment by thanos-wandb** [comment]
Hi @JiarunLiu sorry to hear for the trouble this is currently causing. Could you please go to system settings, click on update license, paste the new license and then click on Update settings once? Then go back to system settings page again and click on `Click here to update` button and `Update settings` again? would this work for you, and if possible to share a screen recording? thank you!

**Comment by JiarunLiu** [comment]
This didn't work for me. Here is my screen recording:

https://github.com/wandb/server/assets/42335666/e5895b4d-1ae6-42c4-916d-07f5525ad86a

**Comment by JiarunLiu** [comment]
@thanos-wandb  Thank you for your help. I can using my local wandb server now. Update the host first then the license does not worked for me. Passing lincense & host as environment variables did works. Thank you.
