### ISSUE TITLE
Should we use the same email and username for both local and public cloud instances?

### ISSUE THREAD

**Issue by zhuoqun-chen** [wandb/server#128]
Hi wandb team,

I know this is a quite trivial question, but I didn't seem other posts that had similar questions so I just ask here. 

If I use the same email, same username to sign up for my local server instance, will it have bad effects on my public cloud credentials? Is it possible that once I use it to login locally, I can't send my experiment logs to the public cloud anymore?

**Comment by luisbergua** [comment]
Hi @zhuoqun-chen, great question! The database of your local instance is completely independent of the public cloud one so there are no restrictions about using the same email/username in both instances. The API key is unique for each one so you will have different credentials (actually one starts with `local-`). Please let me know if that's helpful!

**Comment by sydholl** [comment]
Internal GitHub User commented: 
Hi wandb team,

I know this is a quite trivial question, but I didn't seem other posts that had similar questions so I just ask here. 

If I use the same email, same username to sign up for my local server instance, will it have bad effects on my public cloud credentials? Is it possible that once I use it to login locally, I can't send my experiment logs to the public cloud anymore?

**Comment by zhuoqun-chen** [comment]
Hi @luisbergua, thank you for the quick reply! Very informative and solved my problem.

**Comment by sydholl** [comment]
WandB Internal User commented: 
zhuoqun-chen commented: 
Hi @luisbergua, thank you for the quick reply! Very informative and solved my problem.
