### ISSUE TITLE
How to enable external file storage?

### ISSUE THREAD

**Issue by ericxsun** [wandb/server#131]
I start wandb local, and with a valid license(single user) configured. But I cannot enable `Use an external file storage backend`. 

<img width="786" alt="image" src="https://github.com/wandb/server/assets/1772912/7c29c179-c5cd-4117-843a-f2407a770de0">

Can anyone explain or help me? Thanks very much.

**Comment by JoanaMarieL** [comment]
Hello @ericxsun ,

To enable the 'Use an external file storage backend' feature, you need to navigate to the W&B settings page at http(s)://YOUR-W&B-SERVER-HOST/system-admin. Here, you can enable the option and provide the necessary information about your storage bucket, region, and notification subscription.

For Amazon S3, the format is as follows:
- **File Storage Bucket**: s3://<bucket-name>
- **File Storage Region (AWS only)**: <region>
- **Notification Subscription**: sqs://<queue-name>

For Google Cloud Storage, the format is:
- **File Storage Bucket**: gs://<bucket-name>
- **File Storage Region**: leave this blank
- **Notification Subscription**: pubsub:/<project-name>/<topic-name>/<subscription-name>

After providing the necessary information, select **Update settings** to apply the new settings.

You can also go through with our install guides here: 
for google: 
https://docs.wandb.ai/guides/hosting/how-to-guides/gcp-tf#configure-wb-server
for aws:
https://docs.wandb.ai/guides/hosting/how-to-guides/aws-tf#configure-wb-server

**Comment by ericxsun** [comment]
Thank you @JoanaMarieL . Actually, I'm on the page: http://host/ystem-admin, I can only enable/disable 

- Use an external MySQL instance
- Use an external Redis instance

The `Use an external file storage backend` button is disabled, I cannot enable it by click.

<img width="712" alt="image" src="https://github.com/wandb/server/assets/1772912/1e76d6be-0d25-4690-99b3-853e2895ac29">

**Comment by MBakirWB** [comment]
Hi @ericxsun, for personal users our free deployment license does not allow for Cloud Storage Buckets, and for a single deployment on your machine. These elevated features are only available for our enterprise level users. Let me know if you have any questions.  

![Screenshot 2023-10-27 at 10 39 56 AM](https://github.com/wandb/server/assets/104453360/7ff3f852-09f2-40e1-8b0a-fe08f6460abd)
![image](https://github.com/wandb/server/assets/104453360/e949207e-fad5-4eb1-95e1-422dcc340892)

**Comment by ericxsun** [comment]
> Hi @ericxsun, for personal users our free deployment license does not allow for Cloud Storage Buckets, and for a single deployment on your machine. These elevated features are only available for our enterprise level users. Let me know if you have any questions.
> 
> ![Screenshot 2023-10-27 at 10 39 56 AM](https://user-images.githubusercontent.com/104453360/278720306-7ff3f852-09f2-40e1-8b0a-fe08f6460abd.png) ![image](https://user-images.githubusercontent.com/104453360/278720227-e949207e-fad5-4eb1-95e1-422dcc340892.png)

Okay, I got it. Thanks a lot. @MBakirWB
