### ISSUE TITLE
The weird process 'megabinary' swallows too much memory in the docker

### ISSUE THREAD

**Issue by SwaySZ** [wandb/server#133]
I came across with significant memory usage of the docker (Ubuntu 18.04 and wandb docker 0.44).
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND  
3770 wandb     20   0 1641052 835976  19568 S  22.3  21.6  57:11.14 megabinary                                          
   71 wandb     20   0 2665576 667784   3480 S   0.0  17.2  65:40.84 mysqld   
```

Not sure what the process megabinary is. 

Thanks.

**Comment by nate-wandb** [comment]
Hi @SwaySZ, that should be the main process running the application. Is this causing any issues?

**Comment by SwaySZ** [comment]
> Hi @SwaySZ, that should be the main process running the application. Is this causing any issues? 
Is there possible memory leak? The memory increases too much after several days even though I don't use the service.

**Comment by nate-wandb** [comment]
@SwaySZ when you say you are using `wandb docker 0.44` are you referring to `wandb server` version 0.44.0? Upgrading to latest (0.47.2) should resolve the memory issues

**Comment by nate-wandb** [comment]
Hi @SwaySZ, I just wanted to follow up and see if you had a chance to try out upgrading to the latest version of `wandb server` and if that resolved the memory issue?

**Comment by SwaySZ** [comment]
> Hi @SwaySZ, I just wanted to follow up and see if you had a chance to try out upgrading to the latest version of `wandb server` and if that resolved the memory issue?

I will take a try. Thank you.

**Comment by nate-wandb** [comment]
@SwaySZ of course! Did you have a chance to try this out and did it resolve the memory leak?

**Comment by SwaySZ** [comment]
> WandB Internal User commented:
> nate-wandb commented:
> @SwaySZ when you say you are using `wandb docker 0.44` are you referring to `wandb server` version 0.44.0? Upgrading to latest (0.47.2) should resolve the memory issues

This problem seems solved after upgrading. Thank you.

**Comment by MBakirWB** [comment]
Hi @SwaySZ , thank you for verifying the issue has been resolved. Closing this out but please feel free to reach out anytime we could be of assistance.
