### ISSUE TITLE
How to replace PUBLIC_URL or __PUBLIC_URL_PLACEHOLDER__ in web html?

### ISSUE THREAD

**Issue by youamanb** [wandb/server#136]
how to generate web path in index.html? like  <script src="/mypath/babel-polyfill.min.js"></script> , mypath is self defined

**Comment by nate-wandb** [comment]
Hi @youamanb, I'm not sure I fully understand the question. Could you let me know what your goal is by doing this?

**Comment by youamanb** [comment]
您好，我已收到您的邮件，谢谢！

**Comment by youamanb** [comment]
Hi @nate-wandb ,
I run the wandb-local docker image with version wandb/local:0.50.2, and in the docker container,I found the index.html file under the folder /var/app/frontend, the  "/var/app/frontend/index.html" is generated from "/var/app/orig_frontend/index.html"，and   "__PUBLIC_URL_PLACEHOLDER__" is in /var/app/orig_frontend/index.html.So I want to replace "__PUBLIC_URL_PLACEHOLDER__" with my own defined URL prefix such as “wandb-api”，so I hope the generated file "/var/app/frontend/index.html" has content src path like this " <script src="/wandb-api/raven.min.js" crossorigin="anonymous"></script>"，can we do this？

**Comment by sydholl** [comment]
WandB Internal User commented: 
youamanb commented: 
Hi @nate-wandb ,
I run the wandb-local docker image with version wandb/local:0.50.2, and in the docker container,I found the index.html file under the folder /var/app/frontend, the  "/var/app/frontend/index.html" is generated from "/var/app/orig_frontend/index.html"，and   "__PUBLIC_URL_PLACEHOLDER__" is in /var/app/orig_frontend/index.html.So I want to replace "__PUBLIC_URL_PLACEHOLDER__" with my own defined URL prefix such as “wandb-api”，so I hope the generated file "/var/app/frontend/index.html" has content src path like this " <script src="/wandb-api/raven.min.js" crossorigin="anonymous"></script>"，can we do this？

**Comment by anmolmann** [comment]
Hi @youamanb , you shouldn't need to manually edit these files on your end. Passing the [host variable](https://docs.wandb.ai/guides/hosting/env-vars), the FQD of your instance, i.e. `https://my.domain.net/` should work. Please set the host and then launch your docker container, you'll see we'll populate the placeholder automatically after parsing it from the host var value. If this doesn't happen in your case, please let us know and we'll investigate this further.
Example cmd:
```
\docker run --rm -d \
   -e HOST=https://YOUR_DNS_NAME \
   -e LICENSE=XXXXX \
```

**Comment by youamanb** [comment]
您好，我已收到您的邮件，谢谢！

**Comment by anmolmann** [comment]
Hi @youamanb , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by anmolmann** [comment]
Hi @youamanb , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
