### ISSUE TITLE
How do I move the stored data of wandb local server to another place?

### ISSUE THREAD

**Issue by luo-li-ba-suo** [wandb/server#140]
I tried to move the data volume mounted when wandb docker was started, but when I restarted wandb docker container after the move, an error would be reported, and the original training record would not be displayed

**Comment by ArtsiomWB** [comment]
Hi! Thank you for writing in. Could you please talk a bit more about what stored data you are interested in moving and where you would like to move it? Are you just trying to move the wandb folder? What error are you getting?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
