### ISSUE TITLE
NAS encounters the issue about network slow, that causes the migrate task failure, however, network is normal.

### ISSUE THREAD

**Issue by LiuWhale** [wandb/server#143]
## System
Linux  4.4.302+ #69057 SMP Fri Jan 12 17:02:59 CST 2024 x86_64 GNU/Linux synology_apollolake_918+
## Docker version
- Docker version 20.10.23, build 876964a
## Python version
- 3.11.5
## wandb version
 - 0.18.5

```
docker run --rm -d -e LICENSE=mylicense -p 6009:8080  --name wandb-local wandb/local
```

![Image](https://github.com/user-attachments/assets/44398171-575b-4895-a590-a8751ca8725a)
![Image](https://github.com/user-attachments/assets/6b101bc4-b009-43e0-a62a-9e2eea39c73a)
![Image](https://github.com/user-attachments/assets/181c9513-a2ec-4009-8edf-d34aae11ee3e)

**Comment by luisbergua** [comment]
Hey @LiuWhale, thanks for writing in! Would you mind sharing which version are you running currently? I would recommend ensuring that you're running the latest version (see [here](https://github.com/wandb/server/releases), `0.61.0`). If this still fails, could you please try running the steps [here](https://docs.wandb.ai/guides/hosting/self-managed/basic-setup) and seeing if that causes any issues? By following those you shouldn't face any issue, and can apply the license in the UI so curious to know if this would work for you.

**Comment by LiuWhale** [comment]
> Hey [@LiuWhale](https://github.com/LiuWhale), thanks for writing in! Would you mind sharing which version are you running currently? I would recommend ensuring that you're running the latest version (see [here](https://github.com/wandb/server/releases), `0.61.0`). If this still fails, could you please try running the steps [here](https://docs.wandb.ai/guides/hosting/self-managed/basic-setup) and seeing if that causes any issues? By following those you shouldn't face any issue, and can apply the license in the UI so curious to know if this would work for you.

I tried with wandb command, but an issue is shown as below, that's why run server manually.
![Image](https://github.com/user-attachments/assets/e5983b6d-f2b7-4c72-b20d-e68967e96578)

**Comment by LiuWhale** [comment]
When I try with wandb docker-run command, new issue is showed up.
![Image](https://github.com/user-attachments/assets/53008916-1791-4e9c-9749-e6bf49260d26)

**Comment by luisbergua** [comment]
Thanks for sharing this @LiuWhale! Would you mind sharing what version are you using? Also, I see the image was created 2 weeks ago, so I would recommend removing it and the container and trying again in a fresh environment with the `wandb server start` command. It might be that there's something wrong with your current image

**Comment by LiuWhale** [comment]
![Image](https://github.com/user-attachments/assets/4c9adba1-e94b-40eb-b3b7-e96eb1e97898)
The sandy image is latest version, same as docker hub’s one. The digest code is same too.

> Thanks for sharing this [@LiuWhale](https://github.com/LiuWhale)! Would you mind sharing what version are you using? Also, I see the image was created 2 weeks ago, so I would recommend removing it and the container and trying again in a fresh environment with the `wandb server start` command. It might be that there's something wrong with your current image

**Comment by LiuWhale** [comment]
I’m considering about the influence of system, the image is running well on Ubuntu, after all.

**Comment by luisbergua** [comment]
Hi @LiuWhale, thanks for confirming this! Yes that could be affecting, I would recommend trying in a fresh environment from scratch (and maybe a different machine). Please let me know if you still see the issue after doing that!

**Comment by luisbergua** [comment]
Hey Liu, closing this for now but feel free to re-open if you need any other assistance

**Comment by LiuWhale** [comment]
```
panic: context deadline exceeded
```
when start the container, migrate task is time out, how to set more time for this.

**Comment by luisbergua** [comment]
Hi @LiuWhale, thanks for sharing this. I have been checking with our Product Team, and the general recommendation is using our SaaS offer at https://wandb.ai, since  that's where we provide support for non-paying users. Would you mind letting me know if using it would work for you?

**Comment by LiuWhale** [comment]
> Hi [@LiuWhale](https://github.com/LiuWhale), thanks for sharing this. I have been checking with our Product Team, and the general recommendation is using our SaaS offer at https://wandb.ai, since that's where we provide support for non-paying users. Would you mind letting me know if using it would work for you?
Sure, it works for me.
