### ISSUE TITLE
HOW to storage data to local for wandb server

### ISSUE THREAD

**Issue by emilylxj** [wandb/server#144]
I start wandb server by wandb server start -p 8080 -e HOST=192.168.0.205:8080

and the service is ok.

But how to mount a local volume to service ,to save the data .

**Comment by luisbergua** [comment]
Hey @emilylxj, thanks for your question! You can run docker like:
```
docker run -v ./wandb_data:/vol -p 8080:8080 --name wandb_local wandb/local 
```
See our docs [here](https://docs.wandb.ai/guides/hosting/self-managed/basic-setup#add-a-volume-to-retain-data). Please let me know if this is helpful!

**Comment by luisbergua** [comment]
Hi @emilylxj, just wanted to check if the information I provided was helpful?

**Comment by emilylxj** [comment]
> Hi [@emilylxj](https://github.com/emilylxj), just wanted to check if the information I provided was helpful?

Thank you for your reply . I very sorry for  my reply to you a few days ago didn't get sent successfully. 

As follows:

Yes,If I run server by docker run directly ,this method(
docker run -v ./wandb_data:/vol -p 8080:8080 --name wandb_local wandb/local
) is ok .
But I start my local server by "wandb server start -p 8080 -e HOST=http://192.168.0.205:8080 ",
How to transform the wandb_data directory to docker container ? 
The wandb server, as I understand ,it is a wrapper for wandb_local docker.

**Comment by emilylxj** [comment]
I refer to the document [here](https://docs.wandb.ai/guides/hosting/self-managed/basic-setup/#add-a-volume-to-retain-data). such as ：

![Image](https://github.com/user-attachments/assets/261a2f37-d662-4126-9926-3dd8024ec1a0)

Anyway, my requirement is: to create wandb server in local machine(hostname:192.168.0.205) for group members to use, and the data is also stored in local machine.
Maybe you can give me some better suggestions.

**Comment by luisbergua** [comment]
Thanks for sharing this! The docker command would do the same for you, is there any reason why it wouldn't be an option?

**Comment by luisbergua** [comment]
Hey @emilylxj, just checking if you would need any other assistance here?

**Comment by luisbergua** [comment]
Hi @emilylxj, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by emilylxj** [comment]
Sorry ,

I use the command to start wandb docker ,and mount local data (/home/PublicData/AntiMatterRL/wandb/wandb_data)
`
 docker run -v /home/PublicData/AntiMatterRL/wandb/wandb_data:/vol:d
elegated -p 192.168.0.205:15518:8080 --name wandb_local wandb/local
`

But I get the following error:
*** Running /etc/my_init.d/01_enable-services.sh...
*** Enabling production mode
*** Running /etc/my_init.d/02_load-settings.sh...
mkdir: cannot create directory ‘/vol’: Permission denied
find: ‘/vol/env’: Permission denied
*** Loading settings...
2024/11/22 08:37:42 Error setting password for default user
panic: stat /vol/env/users.htpasswd: permission denied

goroutine 1 [running]:
main.ensureDefaults({{0x2125891, 0x4}, {0x0, 0x0}, {0xc000058016, 0x16}, {0xc0000561b2, 0xa}, {0x214d346, 0x1a}, ...})
        /home/circleci/go/src/github.com/wandb/core/services/local/cmd/local/main.go:635 +0xbd9
main.commands({{0x2125891, 0x4}, {0x0, 0x0}, {0xc000058016, 0x16}, {0xc0000561b2, 0xa}, {0x214d346, 0x1a}, ...})
        /home/circleci/go/src/github.com/wandb/core/services/local/cmd/local/main.go:394 +0x1d25
main.main()
        /home/circleci/go/src/github.com/wandb/core/services/local/cmd/local/main.go:757 +0x78
!!! Failed to load settings. If this issue persists, please contact support@wandb.com.
*** Booting runit daemon...
*** Runit started as PID 50
*** Shutting down runit daemon (PID 50)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
*** Init system aborted.

**Comment by luisbergua** [comment]
Thanks for sharing this @emilylxj, it seems you don't have permissions for `/vol` folder, so you should update that or point to a folder that you have permissions. Separately, I have been checking with our Product Team, and the general recommendation is using our SaaS offer at https://wandb.ai/, since that's where we provide support for non-paying users and have all our features available. Would you mind letting me know if using it would work for you?

**Comment by emilylxj** [comment]
Thank you very much for your reply.
Actually, I don't quite understand. /vol should be the default folder within docker. I just need to map the local folder to /vol. Local folder permissions are open.
 The SaaS product https://wandb.ai/ does have richer functionality, but if I have a lot of data in my group and I need to keep that data locally, how does https://wandb.ai/ solve the problem for the data storage. Maybe you can give me a better suggestion.

Translated with DeepL.com (free version)

**Comment by luisbergua** [comment]
Hey @emilylxj, closing this for now since we haven't heard back. As general advice:
* We always recommend our SaaS option, since we provide support for non-paying users and have all our features available
* If you want to use wandb server, the recommended approach is running `wandb server start` and follow the steps [here](https://docs.wandb.ai/guides/hosting/self-managed/basic-setup), which is the supported way for non-paying users
